// @generated — do NOT edit this file directly. It is generated from
// core/models/src/defaults/EncryptionDefaults.ts by core/models/scripts/generate-encryption-defaults.cjs.
// Edit the TypeScript source and run 'core/models/build.sh' to regenerate.

import Foundation

/// Argon2id key derivation defaults shared across all AliasVault clients.
enum EncryptionDefaults {
    /// Degree of parallelism (lanes) for Argon2id.
    static let argon2idDegreeOfParallelism: UInt32 = 1

    /// Memory cost for Argon2id, in KiB.
    static let argon2idMemorySize: UInt32 = 65536

    /// Number of Argon2id passes over memory.
    static let argon2idIterations: UInt32 = 3

    /// Key derivation algorithm recorded against a vault.
    static let encryptionType: String = "Argon2Id"

    /// The settings exactly as they are stored against a vault. Key order is part of the value.
    static let encryptionSettings: String = "{\"DegreeOfParallelism\":1,\"MemorySize\":65536,\"Iterations\":3}"
}
