// @generated — do NOT edit this file directly. It is generated from
// core/models/src/defaults/EncryptionDefaults.ts by core/models/scripts/generate-encryption-defaults.cjs.
// Edit the TypeScript source and run 'core/models/build.sh' to regenerate.

package net.aliasvault.app

/**
 * Argon2id key derivation defaults shared across all AliasVault clients.
 */
object EncryptionDefaults {
    /** Degree of parallelism (lanes) for Argon2id. */
    const val ARGON2ID_DEGREE_OF_PARALLELISM = 1

    /** Memory cost for Argon2id, in KiB. */
    const val ARGON2ID_MEMORY_SIZE = 65536

    /** Number of Argon2id passes over memory. */
    const val ARGON2ID_ITERATIONS = 3

    /** Key derivation algorithm recorded against a vault. */
    const val ENCRYPTION_TYPE = "Argon2Id"

    /** The settings exactly as they are stored against a vault. Key order is part of the value. */
    const val ENCRYPTION_SETTINGS = "{\"DegreeOfParallelism\":1,\"MemorySize\":65536,\"Iterations\":3}"
}
