//! Argon2id key derivation defaults shared by every AliasVault client.
//!
//! @generated — do NOT edit this file directly. It is generated from
//! core/models/src/defaults/EncryptionDefaults.ts by core/models/scripts/generate-encryption-defaults.cjs.
//! Edit the TypeScript source and run 'core/models/build.sh' to regenerate.

/// Degree of parallelism (lanes) for Argon2id.
pub const ARGON2ID_DEGREE_OF_PARALLELISM: u32 = 1;

/// Memory cost for Argon2id, in KiB.
pub const ARGON2ID_MEMORY_SIZE: u32 = 65536;

/// Number of Argon2id passes over memory.
pub const ARGON2ID_ITERATIONS: u32 = 3;

/// Key derivation algorithm recorded against a vault.
pub const ENCRYPTION_TYPE: &str = "Argon2Id";

/// The settings exactly as they are stored against a vault. Key order is part of the value.
pub const ENCRYPTION_SETTINGS: &str = "{\"DegreeOfParallelism\":1,\"MemorySize\":65536,\"Iterations\":3}";
