// <auto-generated />
// This file is auto-generated from core/models/src/defaults/EncryptionDefaults.ts
// Do not edit this file directly. Run 'core/models/build.sh' (or
// 'node core/models/scripts/generate-encryption-defaults.cjs') to regenerate.

#nullable enable

namespace AliasVault.Cryptography.Client;

/// <summary>
/// Argon2id key derivation defaults shared across all AliasVault clients.
/// </summary>
public static class Argon2Defaults
{
    /// <summary>
    /// Degree of parallelism (lanes) for Argon2id.
    /// </summary>
    public const int Argon2idDegreeOfParallelism = 1;

    /// <summary>
    /// Memory cost for Argon2id, in KiB.
    /// </summary>
    public const int Argon2idMemorySize = 65536;

    /// <summary>
    /// Number of Argon2id passes over memory.
    /// </summary>
    public const int Argon2idIterations = 3;

    /// <summary>
    /// Key derivation algorithm recorded against a vault.
    /// </summary>
    public const string EncryptionType = "Argon2Id";

    /// <summary>
    /// The settings exactly as they are stored against a vault. Key order is part of the value.
    /// </summary>
    public const string EncryptionSettings = "{\"DegreeOfParallelism\":1,\"MemorySize\":65536,\"Iterations\":3}";
}
